multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/nas/longleaf/home/mixarcid/plantain/vina_bigbind.py", line 99, in get_vina_score
    rec_file = prepare_rec(cfg, row.ex_rec_file)
  File "/nas/longleaf/home/mixarcid/plantain/vina_bigbind.py", line 32, in prepare_rec
    prep_cmd = f"{cfg.platform.adfr_dir}/bin/prepare_receptor"
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/_utils.py", line 818, in format_and_raise
    _raise(ex, cause)
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key adfr_dir
    full_key: platform.adfr_dir
    object_type=dict
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nas/longleaf/home/mixarcid/plantain/vina_bigbind.py", line 129, in <module>
    for ret_file in p.imap_unordered(score_fn, screen_df.iterrows()):
  File "/nas/longleaf/home/mixarcid/miniconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
omegaconf.errors.ConfigAttributeError: Missing key adfr_dir
    full_key: platform.adfr_dir
    object_type=dict
